# Configuration for creating lilypond sheet music
# Bank 2
healing:
  title: Healing Pokémon
  grouping:
    - channels: [0]
      clef: treble
    - channels: [1]
      clef: bass
route_01:
  title: Route 1 Theme
  grouping:
    - channels: [1, 2]
      clef: treble
      part_combine: True
    - channels: [0] # channel 3 ignored
      clef: bass
  staff_args:
    repeat: True
  processing:
    0:
      - [transpose_score_octave, { offset: -1 }]
    1:
      - [transpose_score_octave, { offset: 1 }]
    2:
      - [transpose_score_octave, { offset: 1 }]
      - [remove_note, { index: -1 }]
      - [split_notes, { index: [-7, -6, -3, -2] }] # creates channel 3
  tempo: 100
route_03: # needs work, remove deep notes from channel 0
  title: Route 3 Theme
  grouping:
    - channels: [1, 0]
      clef: treble
      part_combine: True
    - channels: [4]
      clef: bass
  staff_args:
    repeat: True
  processing:
    0:
      - combine_rests
      - [transpose_score_octave, { offset: 1 }]
      - [split_notes, { index: [13, 14, 29, 30, -9] }] # creates channel 3
    1:
      - combine_rests
      - [transpose_score_octave, { offset: 1 }]
    2:
      - [eat_rests, { max_dur: 1.0 }]
      - [transpose_score_octave, { offset: -1 }]
  chords: # creates channel 4
    channels: [2, 3]
    type: part_combine
    kwargs:
      errors: raise
  tempo: 120
route_12:
  title: Route 12 Theme
  grouping:
    - channels: [1]
      clef: treble
    - channels: [3]
      clef: bass
  staff_args:
    repeat: True
  processing:
    1:
      - combine_irregular_notes
      - [transpose_score_octave, { offset: 1 }]
    2:
      - [eat_rests, { max_dur: 3.0 }]
      - [transpose_score_octave, { offset: -1 }]
      - [remove_note, { index: ["-11>-9", "-32>-17"] }]
      - combine_rests
  chords: # creates channel 3
    channels: [2, 0]
    type: align_shortest
  tempo: 120
route_25:
  title: Route 25 Theme
  grouping:
    - channels: [1]
      clef: treble
    - channels: [0]
      clef: bass
  staff_args:
    repeat: True
  processing:
    1:
      - [transpose_note_octave, { offset: 1, index: 8 }]
indigo_plateau:
  title: Indigo Plateau
  grouping:
    - channels: [2]
      clef: treble
    - channels: [3]
      clef: bass
  staff_args:
    repeat: True
  chords: # creates channel 3
    channels: [0, 1]
    type: make_chords
pallet_town:
  title: Pallet Town
  grouping:
    - channels: [1]
      clef: treble
    - channels: [0]
      clef: bass
  staff_args:
    repeat: True
  processing:
    0:
      - [transpose_score_octave, { offset: -1 }]
  tempo: 100
viridian_city:
  title: Viridian City
  grouping:
    # - channels: [1, 0]
    #   clef: treble
    #   part_combine: True
    # - channels: [2]
    #   clef: treble
    - channels: [1]
      clef: treble
    - channels: [3]
      clef: treble
  processing:
    0:
      - [transpose_score_octave, { offset: 1 }]
    1:
      - [transpose_score_below, { t_note: "c", t_octave: 4 }]
      - [transpose_score_octave, { offset: 1 }]
  chords: # creates channel 3
    channels: [2, 0]
    type: align_shortest
    kwargs:
      allow_seconds: False
  staff_args:
    repeat: True
  tempo: 120
following_person:
  title: Following Person
prof_oak:
  title: Prof. Oak Encounter
meet_rival_trainer:
  title: Rival Trainer Encounter
ss_anne:
  title: S.S. Anne
cerulean_city:
  title: Cerulean City
celadon_city:
  title: Celadon City
cinnabar_island:
  title: Cinnabar Island
vermilion_city:
  title: Vermilion City
lavender_town:
  title: Lavender Town
safari_zone:
  title: Safari Zone
gyms:
  title: Gym Theme
pokemon_center:
  title: Pokémon Center
# Bank 8
gym_leader_battle:
  title: Gym Leader Battle
battle:
  title: Trainer Battle
wild_pokemon:
  title: Wild Pokémon Battle
final_battle:
  title: Final Battle
defeated_trainer:
  title: Defeated Trainer
defeated_wild_pokemon:
  title: Defeated Wild Pokémon
defeated_gym_leader:
  title: Defeated Gym Leader
# Bank 1f
title:
  title: Title Theme
credits:
  title: Credits
hall_of_fame:
  title: Hall of Fame
prof_oaks_lab:
  title: Prof. Oak's Lab
jigglypuffs_song:
  title: Jigglypuff's Song
bike_riding:
  title: Biking Theme
surfing:
  title: Surfing Theme
casino:
  title: Rocket Game Corner (Celadon City)
title_battle:
  title: Title Battle
rocket_hidehout:
  title: Rocket Hideout (Celadon City)
viridian_forest_seafoam_islands:
  title: Viridian Forest, Seafoam Islands
mt_moon_rock_tunnel_victory_road:
  title: Mt. Moon, Rock Tunnel, Victory Road
pokemon_mansion:
  title: Pokémon Mansion (Cinnabar Island)
pokemon_tower:
  title: Pokémon Tower (Lavender Town)
silph_co:
  title: Silph Co. Office Building (Saffron City)
meet_male_trainer:
  title: Male Trainer Encounter
meet_female_trainer:
  title: Female Trainer Encounter
meet_evil_trainer:
  title: Evil Trainer Encounter
